name: "Lily Dove"
description: "The Research Website for Lily Dove"

url: "lily-dove.github.io"

gems: [jekyll-paginate]
paginate: 6
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
